#ifndef _COMASM_H_
#define _COMASM_H_

#define COM_TXBUF_BITS	6
#define COM_TXBUF_SIZE	(1<<COM_TXBUF_BITS)
#define COM_TXBUF_MASK	(COM_TXBUF_SIZE-1)

#define COM_RXBUF_BITS	4
#define COM_RXBUF_SIZE	(1<<COM_RXBUF_BITS)
#define COM_RXBUF_MASK  (COM_RXBUF_SIZE-1)
#define COM_RXBUFS_BITS	2
#define COM_RXBUFS_NUM	(1<<COM_RXBUFS_BITS)
#define COM_RXBUFS_SIZE (COM_RXBUFS_NUM*COM_RXBUF_SIZE)
#define COM_RXBUFS_MASK (COM_RXBUFS_SIZE-1)

#ifndef __ASSEMBLER__
#endif

#endif
